import { ComboBox, Button, GridBox, Switch, StandardButton, Slider, SpinBox } from "std-widgets.slint";
import { Theme } from "../ui/theme.slint";



export component Label inherits Text {
    in-out property <string> label;
    text: label;
    font-size: Theme.label-size;
    font-weight: Theme.text-weight-bold;
    color: Theme.text-color;
}

export component LevelBox inherits Rectangle {
    in property <string> value;
    in property <bool> delta-mode: true;
    width: Theme.level-box-width;
    height: Theme.level-box-height;

    box-background := Rectangle {
        background: Theme.level-box-background-start;
        border-width: Theme.border-width;
        border-radius: Theme.border-radius;
        border-color: Theme.text-color;
        opacity: 50%;
    }

    Text {
        text: value;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: Theme.levelbox-label-size;
        font-weight: Theme.text-weight-bold;
        color: Theme.text-color;

        changed text => {
            if (!delta-mode || self.text == "-inf") {
                box-background.background = Theme.level-box-background-start;
            } else if (self.text.to-float() < -0.1) {
                box-background.background = Theme.level-box-background-low;
            } else if (self.text.to-float() > 0.1) {
                box-background.background = Theme.level-box-background-high;
            } else {
                box-background.background = Theme.level-box-background-right;
            }
        }
    }
}

export component DeviceSelector inherits Rectangle {
    in-out property <[string]> device_list;
    in-out property <string> current;
    in-out property <int> current_index: selector.current-index;
    callback selected_device(string);

    HorizontalLayout {
        spacing: 10px;

        selector := ComboBox {
            min-width: 275px;
            model: device_list;
            height: Theme.combobox-height;
            current-value: current;
            y: (parent.height / 2) - (self.height / 2);

            selected(value) => {
                root.selected_device(value);
            }
        }
    }
}

export component ChannelSelector inherits Rectangle {
    in-out property <[string]> channel_list;
    in-out property <string> current;
    in property <int> current-index;
    in-out property <bool> enabled: true;
    callback selected_channel(string);

    HorizontalLayout {
        spacing: 10px;
        selector := ComboBox {
            y: (parent.height / 2) - (self.height / 2);
            model: channel_list;
            current-value: current;
            height: Theme.combobox-height;
            enabled: enabled;
            width: 100px;
            selected(value) => {
                root.selected_channel(value);
            }
        }
    }
}

export component Line inherits Rectangle {
    in property <length> length;
    background: Theme.text-color;
    width: 100%;
    height: 1px;
    opacity: 50%;
}

export component ReferenceFrequency inherits Rectangle {
    height: Theme.reference-box-height;
    width: Theme.reference-box-width;
    callback frequency_changed(float);
    in-out property <float> reference_frequency;

    HorizontalLayout {
        alignment: space-around;
        GridLayout {
            Row {
                Text {
                    colspan: 2;
                    text: Theme.reference-tone-header-text;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: Theme.heading-size;
                    font-weight: Theme.text-weight-bold;
                    color: Theme.text-color;
                }
            }

            Row {
                Rectangle {
                    colspan: 2;
                    background: Theme.text-color;
                    height: 2px;
                }
            }

            Row {

                Text {
                    colspan: 2;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: Theme.output-frequency-label;
                    font-size: Theme.label-size;
                    font-weight: 900;
                    color: Theme.text-color;
                }
            }

            Row {
                frequency_spinbox := SpinBox {
                    colspan: 2;
                    minimum: Theme.frequency-minimum;
                    maximum: Theme.frequency-maximum;
                    step-size: Theme.frequency-step-size;
                    value: reference_frequency;

                    edited(frequency) => {
                        root.frequency_changed(frequency);
                    }
                }
            }

            Row {
                Rectangle {
                    colspan: 2;
                    height: 10px;
                }
            }

            Row {
                Text {
                    vertical-alignment: center;
                    text: Theme.output-level-label;
                    font-size: Theme.label-size;
                    font-weight: 900;
                    color: Theme.text-color;
                }

                Text {
                    vertical-alignment: center;
                    text: "-12 dbfs";
                    font-size: Theme.label-size;
                    color: Theme.text-color;
                }
            }

            Row {
                Rectangle {
                    colspan: 2;
                    background: Theme.text-color;
                    height: 2px;
                }
            }
        }
    }
}

export component StartButton inherits Rectangle {
    in-out property <bool> active: false;
    callback tone_start_button_pressed(bool);

    states [
        running when active: {
            start_button.text: Theme.start_button_running;
            start_button.primary: true;
        }
        stopped when !active: {
            start_button.text: Theme.start_button_stopped;
            start_button.primary: false;
        }
    ]

    HorizontalLayout {
        alignment: space-around;
        start_button := Button {
            width: Theme.start-button-width;
            height: Theme.start-button-height;
            clicked => {
                active = !active;
                tone_start_button_pressed(active);
            }
        }
    }
}

export component DeltaModeSwitch inherits Rectangle {
    in-out property <bool> delta_mode: true;
    callback delta_mode_checked(bool);

    HorizontalLayout {
        alignment: center;
        delta_switch := Switch {
            height: Theme.delta-switch-height;
            checked: delta_mode;
            toggled() => {
                root.delta_mode_checked(self.checked);
            }
        }

        Rectangle {
            width: Theme.delta-switch-spacer;
        }

        Label {
            vertical-alignment: center;
            text: delta_switch.checked ? Theme.delta-mode-on-text : Theme.delta-mode-off-text;
            color: delta_switch.checked ? Theme.text-color.brighter(0.3) : Theme.text-color;
        }
    }
}

export component Error inherits Dialog {

    in property <string> message;
    in property <bool> visibility: true;

    callback fatal_error_clicked();

    title: Theme.error-dialog-title;
    visible: visibility;

    TouchArea {
        enabled: true;
        z: 1;
        horizontal-stretch: 1;
        vertical-stretch: 1;
        width: Theme.window-width;
        height: Theme.window-height;

        Rectangle {
            background: Theme.window-background;
            opacity: 0.5;
            padding: 0px;
            width: Theme.window-width * 2;
            height: Theme.window-height * 2;
        }

        Rectangle {
            background: Theme.window-background;
            border-color: Theme.error-text-color;
            border-radius: Theme.border-radius;
            border-width: Theme.border-width;
            width: Theme.error-dialog-width;
            height: Theme.error-dialog-height;
            z: 2.0;

            VerticalLayout {
                alignment: space-between;
                spacing: 30px;
                padding: 20px;

                Label {
                    horizontal-alignment: center;
                    text: Theme.error-dialog-title;
                }

                Text {
                    text: message;
                    wrap: word-wrap;
                    horizontal-alignment: center;
                    color: Theme.text-color;
                    font-size: Theme.heading-size;
                    font-weight: Theme.text-weight-bold;
                }

                HorizontalLayout {
                    alignment: center;
                    StandardButton {
                        kind: ok;
                        width: Theme.error-button-wdith;
                        clicked => {
                            root.fatal_error_clicked();
                        }
                    }
                }
            }
        }
    }
}
