import { HorizontalBox, Button, Switch } from "std-widgets.slint";
import { LevelBox, DeviceSelector, ChannelSelector, ReferenceFrequency, Label, Error, ModeSwitch, AboutPopUp, VersionText} from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";
import { StartButton } from "components.slint";


export component AppWindow inherits Window {
    in property <image> logo: @image-url("../icon/sug_icon.svg");
    icon: logo;
    title: "Stereo Unity Gain";
    min-width: Theme.window-width;
    min-height: Theme.window-height;
    default-font-size: Theme.text-size;
    background: transparent;

    in property <string> version_number;
    in property <string> description;
    in property <string> license;
    in-out property <[string]> input_device_list;
    in-out property <string> current_input_device;
    in-out property <[string]> output_device_list;
    in-out property <string> current_output_device;
    callback selected_input_device(int, string);
    callback selected_output_device(int, string);

    in-out property <[string]> input_channel_list;
    in-out property <string> left_current_input_channel;
    in-out property <string> right_current_input_channel;
    in-out property <[string]> output_channel_list;
    in-out property <string> left_current_output_channel;
    in-out property <string> right_current_output_channel;
    in-out property <bool> right_input_enabled: true;
    in-out property <bool> right_output_enabled: true;
    callback selected_input_channel(string, string);
    callback selected_output_channel(string, string);

    in-out property <string> left_level_box_value: Theme.level-box-default-value;
    in-out property <string> right_level_box_value:  Theme.level-box-default-value;
    in-out property <bool> right_level_box_enabled;

    callback delta_mode_checked(bool);
    in-out property <bool> delta_mode_active: true;

    callback tone_mode_checked(bool);
    in-out property <bool> tone_mode_active: true;

    callback start_button_pressed(bool);
    in-out property <bool> start_button_active;

    callback tone_frequency_changed(float);
    callback tone_level_changed(int);
    in-out property <float> reference_frequency;
    in-out property <int> reference_level;

    in-out property <bool> error-dialog-visible: false;
    in-out property <string> error-message;
    callback close-error-dialog();

    function about-popup() {
        popup.show();
    }

    MenuBar {
        Menu {
            title: @tr("help");
            MenuItem {
                title: @tr("about");
                activated => {
                    about-popup();
                }
            }
        }
    }

    popup := AboutPopUp {
        version: root.version_number;
        description: root.description;
        license: root.license;
    }

    Error {
        message: error-message;
        visibility: error-dialog-visible;
        z: 2.0;
        fatal_error_clicked => {
            root.close-error-dialog();
        }
    }

    Rectangle {
        padding: 4px;
        border-width: Theme.window-border-width;
        background: Theme.window-background;
        border-color: Theme.border-colour;
        border-bottom-left-radius: Theme.border-radius;
        border-bottom-right-radius: Theme.border-radius;

        VerticalLayout {
            horizontal-stretch: 1;
            alignment: start;
            vertical-stretch: 0;

            Rectangle {
                background: Theme.header-background;
                border-width: Theme.border-width;
                border-color: Theme.border-colour;

                HorizontalLayout {
                    alignment: center;
                    spacing: 10px;

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Rectangle { }

                        Label {
                            horizontal-alignment: right;
                            label: "Output:";
                        }

                        Label {
                            horizontal-alignment: right;
                            label: "Input:";
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            label: Theme.left-channel-text;
                        }

                        left_output_channel := ChannelSelector {
                            channel_list: output_channel_list;
                            current: left_current_output_channel;
                            selected_channel(channel) => {
                                root.selected_output_channel(channel, right_output_channel.current);
                                left_current_output_channel = channel;
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }

                        left_input_channel := ChannelSelector {
                            channel_list: input_channel_list;
                            current: left_current_input_channel;
                            selected_channel(channel) => {
                                root.selected_input_channel(channel, right_input_channel.current);
                                left_current_input_channel = channel;
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            horizontal-alignment: center;
                            label: Theme.device-header-text;
                        }

                        output_device := DeviceSelector {
                            device_list: output_device_list;
                            current: current_output_device;
                            selected_device(device) => {
                                root.selected_output_device(self.current_index, device);
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }

                        input_device := DeviceSelector {
                            device_list: input_device_list;
                            current: current_input_device;
                            selected_device(device) => {
                                root.selected_input_device(self.current_index, device);
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            label: Theme.right-channel-text;
                        }

                        right_output_channel := ChannelSelector {
                            channel_list: output_channel_list;
                            current: right_current_output_channel;
                            enabled: right_output_enabled;
                            selected_channel(channel) => {
                                root.selected_output_channel(left_output_channel.current, channel);
                                right_current_output_channel = channel;
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }

                        right_input_channel := ChannelSelector {
                            channel_list: input_channel_list;
                            current: right_current_input_channel;
                            enabled: right_input_enabled;
                            selected_channel(channel) => {
                                root.selected_input_channel(left_input_channel.current, channel);
                                right_current_input_channel = channel;
                                start_button.active = false;
                                root.start_button_pressed(false);
                            }
                        }
                    }
                }
            }

            HorizontalBox {
                padding: 10px;
                alignment: space-around;

                Label {
                    text: Theme.left_box_label;
                    width: left_level_box.width;
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }

                Label {
                    text: Theme.reference-tone-label;
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }

                Label {
                    text: Theme.right_box_label;
                    width: left_level_box.width;
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }
            }

            HorizontalLayout {
                padding: 10px;
                alignment: space-around;
                left_level_box := LevelBox {
                    value: left_level_box_value;
                }

                VerticalLayout {
                    ReferenceFrequency {
                        reference_frequency: root.reference_frequency;
                        reference_level: root.reference_level;
                        frequency_changed(frequency) => {
                            root.tone_frequency_changed(frequency);
                        }
                        level_changed(level) => {
                            root.tone_level_changed(level);
                        }
                    }

                    tone_mode_switch := ModeSwitch {
                        mode-on-text: Theme.tone-mode-on-text;
                        mode-off-text: Theme.tone-mode-off-text;
                        mode_checked(checked) => {
                            root.tone_mode_active = checked;
                            root.tone_mode_checked(checked);
                        }
                    }

                    delta_mode_switch := ModeSwitch {
                        mode-on-text: Theme.delta-mode-on-text;
                        mode-off-text: Theme.delta-mode-off-text;
                        mode_checked(checked) => {
                            root.delta_mode_active = checked;
                            root.delta_mode_checked(checked);
                            left_level_box.delta-mode = checked;
                            right_level_box.delta-mode = checked;
                        }
                    }

                    start_button := StartButton {
                        active: start_button_active;
                        tone_start_button_pressed(active) => {
                            root.start_button_pressed(active);
                        }
                    }
                }

                right_level_box := LevelBox {
                    value: right_level_box_value;
                    enabled: right_level_box_enabled;
                }
            }
            HorizontalLayout {
                padding: 10px;
                VersionText {
                    version_number: version_number;
                }
            }
        }
    }
}
