import { HorizontalBox, Button, Switch } from "std-widgets.slint";
import { LevelBox, DeviceSelector, ChannelSelector, ReferenceFrequency, Label} from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";
import { StartButton } from "components.slint";


export component AppWindow inherits Window {
    title: "Stereo Unity Gain";
    min-width: Theme.window-width;
    min-height: Theme.window-height;
    default-font-size: Theme.text-size;
    background: transparent;

    in-out property <[string]> input_device_list;
    in-out property <string> current_input_device;
    in-out property <[string]> output_device_list;
    in-out property <string> current_output_device;
    callback selected_input_device(int, string);
    callback selected_output_device(int, string);

    in-out property <[string]> input_channel_list;
    in-out property <string> left_current_input_channel;
    in-out property <string> right_current_input_channel;
    in-out property <[string]> output_channel_list;
    in-out property <string> left_current_output_channel;
    in-out property <string> right_current_output_channel;
    in-out property <bool> right_input_enabled: true;
    in-out property <bool> right_output_enabled: true;
    callback selected_input_channel(string, string);
    callback selected_output_channel(string, string);

    in-out property <string> left_level_box_value: "0.0";
    in-out property <string> right_level_box_value: "0.0";

    callback start_button_pressed(bool);
    in-out property <bool> start_button_active;

    Rectangle {
        padding: 4px;
        border-width: Theme.window-border-width;
        background: Theme.window-background;
        border-color: Theme.border-colour;
        border-bottom-left-radius: Theme.border-radius;
        border-bottom-right-radius: Theme.border-radius;

        VerticalLayout {
            horizontal-stretch: 1;
            alignment: start;
            vertical-stretch: 0;

            Rectangle {
                background: Theme.header-background;
                border-width: Theme.border-width;
                border-color: Theme.border-colour;

                HorizontalLayout {
                    alignment: center;
                    spacing: 10px;

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Rectangle { }

                        Label {
                            horizontal-alignment: right;
                            label: "Output:";
                        }

                        Label {
                            horizontal-alignment: right;
                            label: "Input:";
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            label: "Left Channel";
                        }

                        left_output_channel := ChannelSelector {
                            channel_list: output_channel_list;
                            current: left_current_output_channel;
                            selected_channel(channel) => {
                                root.selected_output_channel(channel, right_output_channel.current);
                                left_current_output_channel = channel;
                                start_button.active = false;
                            }
                        }

                        left_input_channel := ChannelSelector {
                            channel_list: input_channel_list;
                            current: left_current_input_channel;
                            selected_channel(channel) => {
                                root.selected_input_channel(channel, right_input_channel.current);
                                left_current_input_channel = channel;
                                start_button.active = false;
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            horizontal-alignment: center;
                            label: "Audio Device";
                        }

                        output_device := DeviceSelector {
                            device_list: output_device_list;
                            current: current_output_device;
                            selected_device(device) => {
                                root.selected_output_device(self.current_index, device);
                                start_button.active = false;
                            }
                        }

                        input_device := DeviceSelector {
                            device_list: input_device_list;
                            current: current_input_device;
                            selected_device(device) => {
                                root.selected_input_device(self.current_index, device);
                                start_button.active = false;
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        Label {
                            label: "Right Channel";
                        }

                        right_output_channel := ChannelSelector {
                            channel_list: output_channel_list;
                            current: right_current_output_channel;
                            enabled: right_output_enabled;
                            selected_channel(channel) => {
                                root.selected_output_channel(left_output_channel.current, channel);
                                right_current_output_channel = channel;
                                start_button.active = false;
                            }
                        }

                        right_input_channel := ChannelSelector {
                            channel_list: input_channel_list;
                            current: right_current_input_channel;
                            enabled: right_input_enabled;
                            selected_channel(channel) => {
                                root.selected_input_channel(left_input_channel.current, channel);
                                right_current_input_channel = channel;
                                start_button.active = false;
                            }
                        }
                    }
                }
            }

            HorizontalBox {
                padding: 10px;
                alignment: space-around;

                Label {
                    text: "Left";
                    width: left_level_box.width;
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }

                Label {
                    text: "Delta From Reference Tone Level";
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }

                Label {
                    text: "Right";
                    width: left_level_box.width;
                    horizontal-alignment: center;
                    font-size: Theme.heading-size;
                }
            }

            HorizontalLayout {
                padding: 10px;
                alignment: space-around;
                left_level_box := LevelBox {
                    value: left_level_box_value;
                }

                VerticalLayout {
                    alignment: start;
                    ReferenceFrequency { }

                    start_button := StartButton {
                        active: start_button_active;
                        tone_start_button_pressed(active) => {
                            root.start_button_pressed(active);
                        }
                    }
                }

                right_level_box := LevelBox {
                    value: right_level_box_value;
                }
            }
        }
    }
}
