
export global Theme {
    out property <length> window-width: 1000px;
    out property <length> window-height: 400px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: #101010;

    out property <color> border-colour: #333333;
    out property <length> border-width: 2px;
    out property <length> border-radius: 15px;

    out property <color> header-background: #252525;
    out property <color> level-box-background-start: #333333;
    out property <color> level-box-background-right: #227722;
    out property <color> level-box-background-low: #222277;
    out property <color> level-box-background-high: #772222;
    out property <length> combobox-height: 25px;
    out property <length> level-box-width: 360px;
    out property <length> level-box-height: 200px;

    out property <color> text-color: #aaaaaa;
    out property <length> text-size: 12px;
    out property <int> text-weight-bold: 800;

    out property <length> label-size: 16px;
    out property <length> levelbox-label-size: 130px;
    out property <length> heading-size: 20px;
}
