
export global Theme {

    out property <string> start_button_running: "Stop";
    out property <string> start_button_stopped: "Start";

    out property <string> reference-tone-label: "Reference Tone";
    out property <string> reference-tone-header-text: "Reference Tone";
    out property <string> left-channel-text: "Left Channel";
    out property <string> device-header-text: "Audio Device";
    out property <string> right-channel-text: "Right Channel";
    out property <string> left_box_label: "Left Level";
    out property <string> right_box_label: "Right Level";
    out property <string> output-level-label: "Output Level (peak dbfs)";
    out property <string> output-frequency-label: "Frequency Hz";
    out property <string> version-text: "version: ";

    out property <length> window-width: 1000px;
    out property <length> window-height: 400px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: #101010;

    out property <color> border-colour: #333333;
    out property <length> border-width: 2px;
    out property <length> border-radius: 15px;

    out property <color> header-background: #252525;
    out property <color> level-box-background-start: #333333;
    out property <color> level-box-background-right: #227722;
    out property <color> level-box-background-low: #222277;
    out property <color> level-box-background-high: #772222;
    out property <length> combobox-height: 25px;
    out property <length> level-box-width: 360px;
    out property <length> level-box-height: 200px;

    out property <color> text-color: #aaaaaa;
    out property <color> greyed-out: #444444;
    out property <length> text-size: 12px;
    out property <int> text-weight-bold: 800;

    out property <length> label-size: 16px;
    out property <length> levelbox-label-size: 130px;
    out property <length> heading-size: 20px;

    out property <length> reference-box-width: 275px;
    out property <length> reference-box-height: 120px;

    out property <length> start-button-width: 100px;
    out property <length> start-button-height: 25px;

    out property <length> delta-switch-width: 250px;
    out property <length> delta-switch-height: 50px;
    out property <length> delta-switch-spacer: 15px;
    out property <string> delta-mode-on-text: "Delta Mode";
    out property <string> delta-mode-off-text: "Peak Mode";

    out property <int> frequency-minimum: 100;
    out property <int> frequency-maximum: 20000;
    out property <int> frequency-step-size: 100;

    out property <int> level-minimum: -30;
    out property <int> level-maximum: 0;
    out property <int> level-step-size: 1;

    out property <color> error-text-color: #992222;
    out property <string> error-dialog-title: "Fatal Error";
    out property <length> error-dialog-width: 400px;
    out property <length> error-dialog-height: 250px;
    out property <length> error-button-wdith: 100px;

    out property <string> about-popup-title: "Stereo Unity Gain";
    out property <string> about-popup-license: "License: ";
    out property <string> about-popup-version: "Version: ";
    out property <color> about-popup-background: window-background.brighter(0.4);
    out property <length> about-popup-border-width: window-border-width;
    out property <length> about-popup-border-radius: border-radius;
    out property <color> about-popup-border-color: border-colour;
    out property <length> about-popup-width: 300px;
    out property <length> about-popup-height: 300px;
    out property <length> about-popup-x: (window-width / 2) - (about-popup-width / 2);
    out property <length> about-popup-y: (window-height / 2) - (about-popup-height / 2);
}
